name: mdaa
services:
  mariadb:
    image: mariadb:10.11
    container_name: base-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: basedb
      MARIADB_USER: devuser
      MARIADB_PASSWORD: devpassword
    ports:
      - "3306:3306"
    volumes:
      - base-mariadb-data:/var/lib/mysql
      - ./docker/init_db/mariadb:/docker-entrypoint-initdb.d:ro
    networks:
      - base-network

  adminer:
    image: adminer:latest
    container_name: base-adminer
    ports:
      - "8082:8080"
    networks:
      - base-network

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    container_name: base-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - base-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: base-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://mariadb:3306/basedb
      KC_DB_USERNAME: devuser
      KC_DB_PASSWORD: devpassword
      KC_HOSTNAME_URL: http://localhost:8080
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    command: [ "start-dev", "--import-realm", "--hostname-strict-https=false" ]
    ports:
      - "8080:8080"
    volumes:
      - ./docker/volumenes/keycloak/realm-basedb.json:/opt/keycloak/data/import/realm-basedb.json:ro
    depends_on:
      - mariadb
    networks:
      - base-network

  backend:
    image: mdaa-backend
    build:
      context: ./_CODIGO/backend
      dockerfile: Dockerfile
    container_name: base-backend
    ports:
      - "8081:8081"
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_DB: basedb
      MARIADB_USER: devuser
      MARIADB_PASSWORD: devpassword
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: basedb
      KEYCLOAK_CLIENT_ID: backend-client
      KEYCLOAK_CLIENT_SECRET: super-secret-backend
      KEYCLOAK_ISSUER_URI: http://localhost:8080/realms/basedb
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/basedb/protocol/openid-connect/certs
      CORS_ALLOWED_ORIGINS: "http://localhost,http://localhost:5173,http://localhost:5174"
      REGISTRATION_REDIRECT_URI: "http://localhost/"
    depends_on:
      - mariadb
      - keycloak
    networks:
      - base-network

  frontend:
    image: mdaa-frontend
    build:
      context: ./_CODIGO/frontend
      dockerfile: Dockerfile
    container_name: base-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - base-network

networks:
  base-network:
    driver: bridge

volumes:
  base-mariadb-data:
