import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, PartialLangiumServices } from 'langium/lsp';
import { inject, type Module } from 'langium';
import { createDefaultModule, createDefaultSharedModule } from 'langium/lsp';
import { DomainModelGeneratedModule, DomainModelGeneratedSharedModule } from './generated/module.js';
import { DomainModelValidator, registerValidator } from './domain-model-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type DomainModelAddedServices = {
    validation: {
        DomainModelValidator: DomainModelValidator
    }
}

/**
 * Union of Langium default services and your custom services - use these services everywhere in your language implementation.
 */
export type DomainModelServices = LangiumServices & DomainModelAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes custom services.
 */
export const DomainModelModule: Module<DomainModelServices, PartialLangiumServices & DomainModelAddedServices> = {
    validation: {
        DomainModelValidator: () => new DomainModelValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in DomainModelModule
 *
 * @param context Optional module context with the ability to inject the Dependency Injection container
 * @return The language-specific services and shared services
 */
export function createDomainModelServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    DomainModel: DomainModelServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        DomainModelGeneratedSharedModule
    ) as LangiumSharedServices;
    const DomainModel = inject(
        createDefaultModule({ shared }),
        DomainModelGeneratedModule,
        DomainModelModule
    ) as DomainModelServices;
    shared.ServiceRegistry.register(DomainModel);
    registerValidator(DomainModel);
    return { shared, DomainModel };
}
