/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiExportLanguageModal: typeof import('./shared/components/modals/AiExportLanguageModal.vue')['default']
    AnalysisCimEditor: typeof import('./modules/analysis/components/AnalysisCimEditor.vue')['default']
    AnalysisCimVisualizer2D: typeof import('./modules/analysis/components/AnalysisCimVisualizer2D.vue')['default']
    AnalysisCimVisualizerJSON: typeof import('./modules/analysis/components/AnalysisCimVisualizerJSON.vue')['default']
    AnalysisMachinesNodeEditor: typeof import('./modules/analysis/components/AnalysisMachinesNodeEditor.vue')['default']
    AnalysisMachinesVisualizer2D: typeof import('./modules/analysis/components/AnalysisMachinesVisualizer2D.vue')['default']
    AnalysisMachinesVisualizerJSON: typeof import('./modules/analysis/components/AnalysisMachinesVisualizerJSON.vue')['default']
    BaseButton: typeof import('./shared/components/base/BaseButton.vue')['default']
    BaseDiffEditor: typeof import('./shared/components/editors/BaseDiffEditor.vue')['default']
    BaseGraph2D: typeof import('./shared/components/visualizers/BaseGraph2D.vue')['default']
    BaseJSONEditor: typeof import('./shared/components/editors/BaseJSONEditor.vue')['default']
    BaseModal: typeof import('./shared/components/BaseModal.vue')['default']
    FlowDraggableEdge: typeof import('./modules/projects/components/FlowDraggableEdge.vue')['default']
    GenericAddEditModal: typeof import('./shared/components/modals/GenericAddEditModal.vue')['default']
    GenericAlertModal: typeof import('./shared/components/modals/GenericAlertModal.vue')['default']
    GenericConfirmDeleteModal: typeof import('./shared/components/modals/GenericConfirmDeleteModal.vue')['default']
    GenericConfirmSaveModal: typeof import('./shared/components/modals/GenericConfirmSaveModal.vue')['default']
    ModuleViewHeader: typeof import('./shared/components/layout/ModuleViewHeader.vue')['default']
    PimCustomEdge: typeof import('./modules/pim/components/PimCustomEdge.vue')['default']
    PimCustomNode: typeof import('./modules/pim/components/PimCustomNode.vue')['default']
    PimEdgeModal: typeof import('./modules/pim/components/PimEdgeModal.vue')['default']
    PimEditor: typeof import('./modules/pim/components/PimEditor.vue')['default']
    PimEditorPalette: typeof import('./modules/pim/components/PimEditorPalette.vue')['default']
    PimEditorProperties: typeof import('./modules/pim/components/PimEditorProperties.vue')['default']
    PimEditorToolbar: typeof import('./modules/pim/components/PimEditorToolbar.vue')['default']
    PimMachineModal: typeof import('./modules/pim/components/PimMachineModal.vue')['default']
    PimNodeModal: typeof import('./modules/pim/components/PimNodeModal.vue')['default']
    PimRelationModal: typeof import('./modules/pim/components/PimRelationModal.vue')['default']
    PimRelationsMachineNode: typeof import('./modules/pim/components/PimRelationsMachineNode.vue')['default']
    PimRelationsVisualEditor: typeof import('./modules/pim/components/PimRelationsVisualEditor.vue')['default']
    PimVisualEditor: typeof import('./modules/pim/components/PimVisualEditor.vue')['default']
    PimVisualizerJSON: typeof import('./modules/pim/components/PimVisualizerJSON.vue')['default']
    ProjectCard: typeof import('./modules/projects/components/ProjectCard.vue')['default']
    ProjectTreeView: typeof import('./modules/projects/components/ProjectTreeView.vue')['default']
    RelationSelector: typeof import('./shared/components/forms/RelationSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundWaveAnimation: typeof import('./shared/components/ui/SoundWaveAnimation.vue')['default']
    SynthSketchIcon: typeof import('./shared/components/icons/SynthSketchIcon.vue')['default']
    ToastContainer: typeof import('./shared/components/ui/ToastContainer.vue')['default']
    TreeNode: typeof import('./modules/projects/components/TreeNode.vue')['default']
    UnsavedChangesModal: typeof import('./shared/components/UnsavedChangesModal.vue')['default']
  }
}
