/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./shared/components/base/BaseButton.vue')['default']
    DeleteConfirmModal: typeof import('./modules/projects/components/DeleteConfirmModal.vue')['default']
    ProjectCard: typeof import('./modules/projects/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundWaveAnimation: typeof import('./shared/components/ui/SoundWaveAnimation.vue')['default']
    ToastContainer: typeof import('./shared/components/ui/ToastContainer.vue')['default']
  }
}
