/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNodeModal: typeof import('./modules/projects/components/AddNodeModal.vue')['default']
    AnalysisCimEditor: typeof import('./modules/analysis/components/AnalysisCimEditor.vue')['default']
    AnalysisCimVisualizer2D: typeof import('./modules/analysis/components/AnalysisCimVisualizer2D.vue')['default']
    AnalysisCimVisualizerJSON: typeof import('./modules/analysis/components/AnalysisCimVisualizerJSON.vue')['default']
    AnalysisMachinesCimEditor: typeof import('./modules/analysis/components/AnalysisMachinesCimEditor.vue')['default']
    AnalysisMachinesNodeEditor: typeof import('./modules/analysis/components/AnalysisMachinesNodeEditor.vue')['default']
    AnalysisMachinesVisualizer2D: typeof import('./modules/analysis/components/AnalysisMachinesVisualizer2D.vue')['default']
    AnalysisMachinesVisualizer3D: typeof import('./modules/analysis/components/AnalysisMachinesVisualizer3D.vue')['default']
    AnalysisMachinesVisualizerJSON: typeof import('./modules/analysis/components/AnalysisMachinesVisualizerJSON.vue')['default']
    AnalysisNodeEditor: typeof import('./modules/analysis/components/AnalysisNodeEditor.vue')['default']
    AnalysisVisualizer2D: typeof import('./modules/analysis/components/AnalysisVisualizer2D.vue')['default']
    AnalysisVisualizer3D: typeof import('./modules/analysis/components/AnalysisVisualizer3D.vue')['default']
    AnalysisVisualizerJSON: typeof import('./modules/analysis/components/AnalysisVisualizerJSON.vue')['default']
    BaseButton: typeof import('./shared/components/base/BaseButton.vue')['default']
    BaseDiffEditor: typeof import('./shared/components/editors/BaseDiffEditor.vue')['default']
    BaseGraph2D: typeof import('./shared/components/visualizers/BaseGraph2D.vue')['default']
    BaseGraph3D: typeof import('./shared/components/visualizers/BaseGraph3D.vue')['default']
    BaseJSONEditor: typeof import('./shared/components/editors/BaseJSONEditor.vue')['default']
    BaseModal: typeof import('./shared/components/BaseModal.vue')['default']
    ConfirmDeleteModal: typeof import('./modules/projects/components/ConfirmDeleteModal.vue')['default']
    DeleteConfirmModal: typeof import('./modules/projects/components/DeleteConfirmModal.vue')['default']
    FlowDraggableEdge: typeof import('./modules/projects/components/FlowDraggableEdge.vue')['default']
    GenericAddEditModal: typeof import('./shared/components/modals/GenericAddEditModal.vue')['default']
    GenericAlertModal: typeof import('./shared/components/modals/GenericAlertModal.vue')['default']
    GenericConfirmDeleteModal: typeof import('./shared/components/modals/GenericConfirmDeleteModal.vue')['default']
    MachineVisualizer2D: typeof import('./modules/projects/components/MachineVisualizer2D.vue')['default']
    MachineVisualizer3D: typeof import('./modules/projects/components/MachineVisualizer3D.vue')['default']
    MachineVisualizerJSON: typeof import('./modules/projects/components/MachineVisualizerJSON.vue')['default']
    ModuleViewHeader: typeof import('./shared/components/layout/ModuleViewHeader.vue')['default']
    NodeEditor: typeof import('./modules/projects/components/NodeEditor.vue')['default']
    ProjectCard: typeof import('./modules/projects/components/ProjectCard.vue')['default']
    ProjectTreeView: typeof import('./modules/projects/components/ProjectTreeView.vue')['default']
    RelationSelector: typeof import('./shared/components/forms/RelationSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundWaveAnimation: typeof import('./shared/components/ui/SoundWaveAnimation.vue')['default']
    SynthSketchIcon: typeof import('./shared/components/icons/SynthSketchIcon.vue')['default']
    ToastContainer: typeof import('./shared/components/ui/ToastContainer.vue')['default']
    TreeNode: typeof import('./modules/projects/components/TreeNode.vue')['default']
    UnsavedChangesModal: typeof import('./shared/components/UnsavedChangesModal.vue')['default']
  }
}
